# Generated by Django 2.1.7 on 2019-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=50)),
                ('book_type', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('uid', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_timestamp', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('book_id', models.IntegerField()),
                ('record_type', models.CharField(max_length=50)),
                ('money', models.DecimalField(decimal_places=2, max_digits=9)),
                ('category', models.CharField(max_length=45)),
                ('note', models.CharField(blank=True, max_length=45)),
                ('create_timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialBook',
            fields=[
                ('s_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=50)),
                ('book_type', models.CharField(max_length=50)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ManyToManyField(blank=True, to='api.Book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('portrait', models.URLField(blank=True)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('group_id_array', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
