# Generated by Django 2.1.7 on 2019-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('uid', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=50)),
                ('book_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('uid', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('book_id', models.IntegerField()),
                ('record_type', models.CharField(max_length=50)),
                ('money', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('portrait', models.URLField()),
                ('uid', models.CharField(max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=9)),
                ('group_id_array', models.CharField(max_length=255)),
            ],
        ),
    ]
