# Generated by Django 2.1.7 on 2019-03-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='budget',
        ),
        migrations.AddField(
            model_name='book',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(default='food', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='note',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.URLField(blank=True, null=True),
        ),
    ]
