# Generated by Django 2.1.7 on 2019-03-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='budget',
        ),
        migrations.AddField(
            model_name='book',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
