# Generated by Django 2.1.7 on 2019-03-21 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='budget',
        ),
        migrations.AddField(
            model_name='book',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(default='food', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='note',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_id_array',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
