# Generated by Django 2.1.7 on 2019-03-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(default='food', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_id_array',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.URLField(blank=True),
        ),
    ]
