# Generated by Django 2.1.7 on 2019-03-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190320_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_id_array',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
