# Generated by Django 2.1.7 on 2019-03-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190314_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
