# Generated by Django 2.1.7 on 2019-03-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190319_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
