# Generated by Django 2.1.7 on 2019-03-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190321_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
    ]
