# Generated by Django 2.1.7 on 2019-04-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_group_id_array'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedInfo',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('info_content', models.TextField()),
                ('climb_url', models.URLField(blank=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('wish_id', models.AutoField(primary_key=True, serialize=False)),
                ('wish_type', models.CharField(max_length=50)),
                ('wish_name', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('create_timestamp', models.DateTimeField(null=True)),
                ('update_timestamp', models.DateTimeField(null=True)),
                ('note', models.CharField(max_length=45)),
                ('money', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_finished', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='specialbook',
            name='username',
        ),
        migrations.AddField(
            model_name='book',
            name='is_shared',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
