# Generated by Django 2.1.7 on 2019-03-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190321_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='date',
            new_name='update_time',
        ),
    ]
