# Generated by Django 2.1.7 on 2019-03-20 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190320_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
