# Generated by Django 2.1.7 on 2019-04-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190409_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_id',
        ),
        migrations.AddField(
            model_name='collection',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
