# Generated by Django 2.1.7 on 2019-03-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190321_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='create_time',
            new_name='create_timestamp',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='update_time',
            new_name='update_timestamp',
        ),
    ]
