# Generated by Django 2.1.7 on 2019-03-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_record_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(default='food', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='note',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
