# Generated by Django 2.1.7 on 2019-03-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190321_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialBook',
            fields=[
                ('s_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=50)),
                ('book_type', models.CharField(max_length=50)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Book')),
            ],
        ),
    ]
