# Generated by Django 2.1.7 on 2019-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190319_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.URLField(blank=True, null=True),
        ),
    ]
