# Generated by Django 2.1.7 on 2019-03-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_specialbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialbook',
            name='s_book_label',
            field=models.CharField(default='gan', max_length=200),
            preserve_default=False,
        ),
    ]
