# Generated by Django 2.1.7 on 2019-04-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190413_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='portrait',
            field=models.URLField(blank=True),
        ),
    ]
