# Generated by Django 2.1.7 on 2019-04-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190416_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedinfo',
            name='first_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recommendedinfo',
            name='second_category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
