# Generated by Django 2.1.7 on 2019-04-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190416_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='recommend_info_id',
            new_name='info_id',
        ),
    ]
