# Generated by Django 2.1.7 on 2019-04-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_record_book_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordRecommend',
            fields=[
                ('record_recommend_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_type', models.CharField(max_length=50)),
                ('record_recommend', models.TextField()),
            ],
        ),
    ]
